# Generated by Django 3.0.4 on 2020-11-23 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('category_slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=350, unique=True, verbose_name='Title')),
                ('blog_slug', models.SlugField(default=1, max_length=350)),
                ('blog_title_tag', models.CharField(max_length=350, verbose_name='Title Tag')),
                ('blog_body', models.TextField(verbose_name='Body')),
                ('blog_published', models.DateTimeField(auto_now_add=True)),
                ('blog_updated', models.DateTimeField(auto_now=True)),
                ('blog_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('blog_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
    ]
