# Generated by Django 3.0.4 on 2020-11-25 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20201123_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_like',
            field=models.ManyToManyField(related_name='blog_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
